### ISSUE TITLE
Error "Property xxx not found in class yyy" on many properties, where the property exists in the class

### ISSUE THREAD

**Issue by peter-urbanus** [mybatis/mybatipse#100]
For instance, these properties were al marked with error:
```
  <resultMap id="programCall" type="nl.mediacenter.xref.dal.ProgramCall">
    <result property="calledProgram"      column="CALLED_PROGRAM"      jdbcType="CHAR"/>
    <result property="calledProgramType"  column="CALLED_PROGRAMTYPE"  jdbcType="CHAR"/>
    <result property="calledProgramText"  column="CALLED_PROGRAMTEXT"  jdbcType="CHAR"/>
    <result property="callingProgram"     column="CALLING_PROGRAM"     jdbcType="CHAR"/>
    <result property="callingProgramType" column="CALLING_PROGRAMTYPE" jdbcType="CHAR"/>
    <result property="callingProgramText" column="CALLING_PROGRAMTEXT" jdbcType="CHAR"/>
  </resultMap>
```
And this is part of the class in question
```
package nl.mediacenter.xref.dal;

public class ProgramCall
{
public String calledProgram;
private String calledProgramType;
private String calledProgramText;
private String callingProgram;
private String callingProgramType;
private String callingProgramText;
public String getCalledProgram()
{
	return calledProgram;
}
public String getCalledProgramType()
{
	return calledProgramType;
}
public String getCalledProgramText()
{
	return calledProgramText;
}
```
As you can see, all the properties are there. The errors went away after I uninstalled MyBatipse.

**Comment by harawata** [comment]
Thank you for the report, @peter-urbanus !

A few quick things that might fix the problem:

- Re-open the editor
- Clean project
- Restart Eclipse

If none of them didn't resolve the issue, please try the followings and let me know the results:

1. Do the other features like auto-completion work?
2. When you import the [jpetstore](https://github.com/mybatis/jpetstore-6) project, do you get the similar validation errors?

**Comment by purbanus** [comment]
Hi @Hirawate, sorry for taking so long to respond. I recently installed MyBatipse and I have the same problem. I tried all your suggestions with no result. I also imported the jpetstore project, and it didn't have any errors. However, this may be because jpetstore doesn't use any &lt;resultMap&gt;.
I do have some news though: I have the errors in a handwritten mapper.xml file, _but in xml generated by MyBatis Generator, which uses &lt;resultMap&gt;, there are no errors!_. Both mappers are in the same project.

Again as previously, the errors went away after I uninstalled MyBatipse

**Comment by purbanus** [comment]
You can ask me anything :-)

**Comment by purbanus** [comment]
Here is the XML of the mapper that has the errors:
```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" 
"http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="pu.heavymetal.dal.queries.QueriesMapper">
  <resultMap id="jaarDocument" type="pu.heavymetal.bo.JaarDocument">
    <result property="jaar"      column="JAAR"    jdbcType="INTEGER"/>
    <result property="issues"    column="ISSUES"  jdbcType="INTEGER"/>
  </resultMap>
```
Here, both properties can't be found with a message like this: `Property 'jaar' not found in class pu.heavymetal.bo.JaarDocument`. Here is the generated XML that has no errors:
```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="pu.heavymetal.dal.generated.AuteurDalMapper">
  <resultMap id="BaseResultMap" type="pu.heavymetal.dal.generated.AuteurDal">
     <id column="id" jdbcType="INTEGER" property="id" />
    <result column="naam" jdbcType="VARCHAR" property="naam" />
  </resultMap>
```
Do you want me to show the java code?

**Comment by harawata** [comment]
Thanks for the info @purbanus ,

Try copying the `BaseResultMap` in the OK mapper and paste it into the NG mapper (i.e. `QueriesMapper`) and see if MyBatipse reports the error or not.

**Comment by purbanus** [comment]
Ok, I did that, and it gives no errors! Here is the XML:
``` 
<mapper namespace="pu.heavymetal.dal.queries.QueriesMapper">
 <resultMap id="BaseResultMap" type="pu.heavymetal.dal.generated.AuteurDal">
    <id column="id" jdbcType="INTEGER" property="id" />
    <result column="naam" jdbcType="VARCHAR" property="naam" />
  </resultMap>
  <resultMap id="jaarDocument" type="pu.heavymetal.bo.JaarDocument">
    <result property="jaar"      column="JAAR"    jdbcType="INTEGER"/>
    <result property="issues"    column="ISSUES"  jdbcType="INTEGER"/>
  </resultMap>
```
So the BaseResultMap has no errors, the jaarDocument has two. I still have no idea.

**Comment by harawata** [comment]
One step closer. :)
Now we know that the difference lies between those two classes.

It is worth checking the directory structure in Finder/File Explorer.
It should look like this:

<img width="213" alt="image" src="https://user-images.githubusercontent.com/149268/144690020-a7676e90-e117-47ff-ba59-8206b8f326c4.png">

But sometimes, users create a directory (i.e. package) that contains a dot.

<img width="198" alt="image" src="https://user-images.githubusercontent.com/149268/144690124-7620095c-e41b-48aa-9850-fc165508ed9f.png">

It could be something else, but compare these classes carefully and you'll find the answer.

**Comment by purbanus** [comment]
I'm afraid not. Here is a screenshot of the directory structure
![Screenshot from 2021-12-04 02-00-58](https://user-images.githubusercontent.com/9484293/144690746-f0945a9a-90c4-46c1-ba09-32dc54ca28a9.png)
e

**Comment by harawata** [comment]
It's Eclipse, right? 
Did you check it in the system's file explorer?

**Comment by purbanus** [comment]
This is indeed Eclipse. Here is the same screenshot of the file system:
![Screenshot from 2021-12-04 02-17-49](https://user-images.githubusercontent.com/9484293/144691343-bb4077f0-50fe-4a13-ad4f-9f70f5d4e4e9.png)

**Comment by harawata** [comment]
Well, could you post the content of `JaarDocument.java`?

**Comment by purbanus** [comment]
Sure, there you go
```
package pu.heavymetal.bo;

public class JaarDocument
{
private final int jaar;
private final long issues;
public JaarDocument( Integer aJaar, Long aIssues )
{
	super();
	jaar = aJaar;
	issues = aIssues;
}
public int getJaar()
{
	return jaar;
}
public long getIssues()
{
	return issues;
}

}
```
Oh, now I see: it's the `final` in the member definitions. If I remove that the errors go away!

**Comment by harawata** [comment]
In that case, you need to use 'constructor mapping'.

```xml
<resultMap id="jaarDocument" type="pu.heavymetal.bo.JaarDocument">
  <constructor>
    <arg column="JAAR" javaType="java.lang.Integer" />
    <arg column="ISSUES" javaType="java.lang.Long" />
  </constructor>
</resultMap>
```

The types of constructor args should match the field types, BTW.


Please see the doc for the details.
https://mybatis.org/mybatis-3/sqlmap-xml.html#constructor

**Comment by purbanus** [comment]
That seems to solve the problem. However, MyBatis has no problem using the immutable class, it's only MyBatipse that has a problem with that. If I uninstall MyBatipse everything runs fine.

**Comment by harawata** [comment]
MyBatis sets values to final fields uses reflection, but you really should not rely on that 'feature' as JDK gets stricter.

**Comment by purbanus** [comment]
Ok, I will accept your answer as the `final` answer, so you can close the problem. Thanks a lot for your time!

**Comment by harawata** [comment]
Thank you for taking the time to report the issue! 👍
