### ISSUE TITLE
Mybatis Proposals preventing use of non-blocking completion.

### ISSUE THREAD

**Issue by tkvangorder** [mybatis/mybatipse#102]
I just installed Eclipse 2020-06 and would like to take advantage of the new "Enable non-blocking completion" feature of the Java Content Assist.

I am seeing the following warning: 

`Preferences->Java->Editor->Content Assist->Advanced`

![image](https://user-images.githubusercontent.com/1878529/85070134-22fee000-b16a-11ea-9e16-33bb89c29e81.png)

**Comment by zhaoyansong0724** [comment]
I have the same problem

**Comment by harawata** [comment]
Hi @tkvangorder @zhaoyansong0724 ,
Thanks for the report and the comment!
This should be fixed in 1.2.4.
Please let me know if you still have the same problem.
