### ISSUE TITLE
Fix needed for eclipse marketplace listing

### ISSUE THREAD

**Issue by thejjw** [mybatis/mybatipse#109]
Hello,

I'm trying to install mybaptise through Eclipse Marketplace but the install fails as the repository at dl.bintray.com cannot be reached as seen from the link below:
https://www.eclipse.org/setups/marketplace/?id=1467819

I have checked https://bintray.com/ and it says the service has been sunset since the beginning of this month.

Could you consider providing directions (in your README, maybe?) as to how one can download plugin release from github and install onto eclipse manually?

It would be best if the marketplace listing can be fixed with new repository link but I would assume that such fix might take some time so any way to allow installation would be very helpful.

Thanks.

**Comment by harawata** [comment]
Yeah, I thought I migrated the repository to JFrog, but my account had been cancelled for inactivity.
I am now waiting for a response from the support and am also looking for an alternative service.
I'm really sorry about the inconvenience!

**Comment by harawata** [comment]
Hi @thejjw ,

Re-migrated to JFrog.
The install button on the marketplace page should work now.
I also updated the update site URL on [README](https://github.com/mybatis/mybatipse#installation).

Please let me know if you have any difficulty!
