### ISSUE TITLE
custom dtd location not supported

### ISSUE THREAD

**Issue by OverDrone** [mybatis/mybatipse#110]
Hello!
I'm behind firewall and I don't have access to internet resources like http://mybatis.org/dtd/mybatis-3-mapper.dtd
I've changed all my mybatis xml files to other internal location:
`<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://internalhost:port/url/mybatis-3-mapper.dtd">`
And after those changes this plugin stopped working completely, says `Content Assist not available at current location`. I had to add xml mapping rule (which needs to be performed now on every developer eclipse instance), without this action xml content assist would stop working.
Please make this plugin work even if I specified custom location for `.dtd` file

**Comment by harawata** [comment]
Hello @OverDrone ,

In Eclipse, you should add a custom 'XML Catalog' to solve that issue.
The following setting assumes that the mybatis project is imported to your workspace, but it would be possible to specify the internal resource URL as the 'Alternative web address' instead.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/149268/143410618-79bb33e8-c93c-4e3c-a540-66acf5370a50.png">

FYI, at runtime, MyBatis reads the DTD in its JAR and does not access the URL.

**Comment by OverDrone** [comment]
> In Eclipse, you should add a custom 'XML Catalog' to solve that issue.

I wouldn't say it's a solution because it must be done on each developer IDE of my team. I frankly don't understand why you even bother checking dtd location because you have ID `-//mybatis.org//DTD Mapper 3.0//EN` to uniquely identify xml file as mybatis mapper. XSD/DTD location was always environment user specific setting, you should never assume any value there. All those `XML Catalog` settings are mostly for the case when you don't control XML file contents, want to cache some schemas workspace wide, etc.
> FYI, at runtime, MyBatis reads the DTD in its JAR and does not access the URL.

Yes, I'm aware but this doesn't help me during development, that's why I installed this plugin in a first place.

**Comment by OverDrone** [comment]
I did some digging and it seems it's how eclipse plugin system works. Although DTDs references have public ID in them, it's not used by eclipse xml parser for some reason and you can only reference dtd system id in plugin.xml. I don't think I have it in me to ask eclipse team to change plugin.xml format, so you may consider this issue closed and blame hardcode of dtd system id on eclipse.
