### ISSUE TITLE
Parameter properties Content Assistance doesn't work on STS 4 or Eclipse

### ISSUE THREAD

**Issue by sayseakleng** [mybatis/mybatipse#111]
*** Parameter properties : #{} and ${} in select/insert/udpate/delte statements. Also works in some attributes.
- Expected:
![image](https://user-images.githubusercontent.com/19582007/145507262-b0b91e4e-4454-4088-a93b-288a37912b9d.png)

- On STS
![image](https://user-images.githubusercontent.com/19582007/145507204-008127b0-036d-4a5c-ad3c-912de713a1f4.png)

*** jdbcType proposal doesn't work unless I added spaces between **=**
<img width="558" alt="image" src="https://user-images.githubusercontent.com/19582007/145509436-a4d03b13-48b9-44be-aa7e-4e48bcaff385.png">

My testing IDEs: 
- Spring Tool Suite 4, Version: 4.12.1.RELEASE
- Eclipse: Version: 2021-03 (4.19.0)

**Comment by sayseakleng** [comment]
I wanted to added that, both issues fixed if added space.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/19582007/145511385-018dabd6-bbcb-456e-8610-a6f228a63517.png">

**Comment by harawata** [comment]
Hello @sayseakleng ,

It's basically the issue field as #106 , I think.
I plan to look for an easy fix, but haven't found the time.
I'm really sorry about the inconvenience.
