### ISSUE TITLE
Add text block processing

### ISSUE THREAD

**Issue by alexinsmail** [mybatis/mybatipse#113]
JEP 378 (Text Blocks) https://openjdk.org/jeps/378
Class JavaQuickAssistProcessor read only _ASTNode.STRING_LITERAL_ and _ASTNode.ARRAY_INITIALIZER_. Does not analyze the text block _ASTNode.TEXT_BLOCK_.

**Comment by harawata** [comment]
Just a quick update: I have briefly looked into it, but there seems to be a bug in the API and `node.getValue()` returns "null literal" (i.e. `ASTNode.NULL_LITERAL`) when we use text block. 😫
I'll see what I can do, but it might take some time until this gets fixed.

**Comment by harawata** [comment]
Hi @alexinsmail ,

It turns out that JDT is working fine.
The latest release 1.3.0 should be able to handle quick assists and content assist (a.k.a. auto completion) on/in JEP 378 text block.
Thank you for the report!
