### ISSUE TITLE
Eclipse install error：Could not find https://github.com/harawata/eclipse-site/

### ISSUE THREAD

**Issue by kafecat** [mybatis/mybatipse#116]
URL INSTALL ：Eclipse install error：Could not find https://github.com/harawata/eclipse-site/.
Market install ：No repository found at https://github.com/harawata/eclipse-site/.

**Comment by kafecat** [comment]
Spring Tool Suite 4 

Version: 4.19.0.RELEASE
Build Id: 202306150758

**Comment by harawata** [comment]
Hello @kafecat ,

Oops. Corrected the URL in README and Maerketplace.
https://harawata.github.io/eclipse-site/
Could you add a comment or just close this issue once you verify the fix?

Thank you very much for letting me know!

**Comment by hazendaz** [comment]
Seems ok now.  I have it already installed but switching to new location states its up to date.

**Comment by harawata** [comment]
Thank you, @hazendaz !

@kafecat 
I'll close this, but please let me know if you have any difficulty.
Thanks again for the report!
