### ISSUE TITLE
XML Editor does not enhance

### ISSUE THREAD

**Issue by zhoujianboy** [mybatis/mybatipse#25]
Mybatis Natrue have benn add  to a project, but the XML Editor does not enhance. 

Such as “Auto-completion” and "Auto-completion".

Thanks!

**Comment by ArcanBusiness** [comment]
that worked for me.
Thanks,

**Comment by harawata** [comment]
@ArcanBusiness Thank you for the feedback!
Hope it worked for @zhoujianboy , too.

**Comment by kazuki43zoo** [comment]
Close because of no reply longer. If you cannot resolve this issue, please reopen this at any time.
