### ISSUE TITLE
(move annotation statement to XML) Add attribute parameterType

### ISSUE THREAD

**Issue by alexey-su** [mybatis/mybatipse#55]
Move annotation statement to XML mapper

Example for update
```
@Update({
  "UPDATE PURCHASEMETHOD SET ",
  "JSON_TEMPLATES = #{json, jdbcType=CLOB, typeHandler=org.apache.ibatis.type.ClobTypeHandler}",
  "WHERE ID = #{id, jdbcType=VARCHAR}"
})
void updateTemplates(@Param("id") String id, @Param("json") String json);
```
Create tag update
```  
<update id="updateTemplates">
  UPDATE PURCHASEMETHOD SET JSON_TEMPLATES = #{json,
  jdbcType=CLOB, typeHandler=org.apache.ibatis.type.ClobTypeHandler}
  WHERE ID = #{id, jdbcType=VARCHAR}
</update>
```
Add attribute parameterType="map"
```
<update id="updateTemplates" parameterType="map">
```

Next example 
```
@Select("SELECT ID, CODE, NAME FROM PURCHASEMETHOD WHERE ID = #{methodId, jdbcType=VARCHAR}")
@ResultMap("mapPurchaseMethod")
List<PurchaseMethod> selectPurchases(String methodId);
```
Create tag "select"
```  
<select id="selectProtocols" resultMap="mapPurchaseMethod">
  SELECT ID, CODE, NAME FROM PURCHASEMETHOD WHERE
  OWNER_ID = #{methodId, jdbcType=VARCHAR}
</select>
```
Add attribute parameterType="string"
```
<select id="selectPurchases" resultMap="mapPurchaseMethod" parameterType="string">
```

**Comment by harawata** [comment]
Thanks for the suggestion, @alexey-su !
But ```parameterType``` is not used anymore. It is better to omit it if you don't need it, right?

**Comment by alexey-su** [comment]
I read the documentation "Mapper XML Files"
http://www.mybatis.org/mybatis-3/sqlmap-xml.html

Attribute "parameterType"
	The fully qualified class name or alias for the parameter that will be passed into this statement. This attribute is optional because MyBatis can calculate the TypeHandler to use out of the actual parameter passed to the statement. Default is unset.

It's use for TypeHandler. Is not it so?

If MyBatis annotations read, he knows transmitted types.
When you read the XML interface, data types are not analyzed.
Maybe I'm wrong.

**Comment by harawata** [comment]
Here is what happens.

- If you omit parameterType, MyBatis uses the actual runtime parameter type.
- If you specified the right parameterType, the result will be the same as the above.
- If you specified a wrong parameterType, the statement will fail.

So, it is better/safer to omit parameterType.
Does it make sense?

Regards,
Iwao

**Comment by alexey-su** [comment]
I agree with your opinion. I noticed a strange value resultType
```
@Select("SELECT DOCUMENT_ID FROM DOCUMENT_FIELDS WHERE NAME=${name, jdbcType=VARCHAR} AND VALUE=${value, jdbcType=VARCHAR}")
List<String> findDocumentsByField(@Param("name") String fieldName, @Param("value") String fieldValue);
```
result xml
```
<select id="findDocumentsByField"
	resultType="java.util.List&lt;java.lang.String&gt;">
	SELECT DOCUMENT_ID FROM DOCUMENT_FIELDS WHERE NAME=${name,
	jdbcType=VARCHAR} AND VALUE=${value, jdbcType=VARCHAR}
</select>
```
I am confused resultType value attribute. I've always done resultType="string".

**Comment by harawata** [comment]
Yes, supporting various return type is on my TODO list.
I'll create a new ticket and work on it later.
Thank you for the feedback!
