### ISSUE TITLE
Eclipse Neon 4.6.0 not supported

### ISSUE THREAD

**Issue by newpanjing** [mybatis/mybatipse#62]
eclipse neon 4.6.0 not supported。

**Comment by harawata** [comment]
Hi @newpanjing ,

What do you mean by 'not supported'?
Cannot install? or it is installed but some features are not working?

It is working fine with Neon on my Mac (Mac OS X 10.11.6 / JDK 8u101).

Does anyone have a similar issue?

**Comment by newpanjing** [comment]
It can be installed. But it does not work after installation. I use eclipse 4.5 This version can be.

**Comment by harawata** [comment]
Is your Neon 'Eclipse IDE for Java EE Developers' version?
It includes the required dependencies, please try that if you haven't.

Do you see any mybatipse related errors in `.log` file in your workspace directory?

**Comment by newpanjing** [comment]
Yes.Eclipse version is
Eclipse Java EE IDE for Web Developers.
Version: Neon Release (4.6.0)
Build id: 20160613-1800

We did not find the log in my work space. But it prompts is already installed. You are now using the 4.6 version of it?
I am now macos 10.12, jdk "1.8.0_65"

**Comment by harawata** [comment]
Yes, I am using MyBatipse on exactly the same version of Neon.
Mac OS 10.11.6, JDK 1.8.0_101.

By the way, `.log` may be invisible in Finder.

**Comment by newpanjing** [comment]
Thank you, I just re-installed it, and switch to a new workspace has been successfully installed, and can be used as normal.

**Comment by harawata** [comment]
Glad to know the problem is resolved!
