### ISSUE TITLE
Allow wildcards in Type Alias setting

### ISSUE THREAD

**Issue by ylx252** [mybatis/mybatipse#68]
The first entry registers all the classes in com.*.domain package as type aliases. ant expression.

**Comment by harawata** [comment]
Wildcard is allowed only when specifying packages.

p.s.
The type alias setting is now editable =D  

<img width="647" alt="20161226-edit-type-alias" src="https://cloud.githubusercontent.com/assets/149268/21471923/df59694e-cb06-11e6-9620-bc9544d30bb3.png">

**Comment by ylx252** [comment]
Need to update the plugin?



d3leaf@126.com
 
From: Iwao AVE!
Date: 2016-12-26 00:04
To: mybatis/mybatipse
CC: ylx252; Author
Subject: Re: [mybatis/mybatipse] Allow wildcards in Type Alias setting (#68)
Wildcard is allowed only when specifying packages.
p.s.
The type alias setting is now editable =D

**Comment by harawata** [comment]
Yes. You need to update MyBatipse to 1.0.24.

**Comment by ylx252** [comment]
Do you have the latest update or download address? Please give one, thank you.



d3leaf@126.com
 
From: Iwao AVE!
Date: 2016-12-26 09:31
To: mybatis/mybatipse
CC: ylx252; Author
Subject: Re: [mybatis/mybatipse] Allow wildcards in Type Alias setting (#68)
Yes. You need to update MyBatipse to 1.0.24.

**Comment by ylx252** [comment]
You README.md not updated.



d3leaf@126.com
 
From: Iwao AVE!
Date: 2016-12-26 09:31
To: mybatis/mybatipse
CC: ylx252; Author
Subject: Re: [mybatis/mybatipse] Allow wildcards in Type Alias setting (#68)
Yes. You need to update MyBatipse to 1.0.24.

**Comment by harawata** [comment]
To update plugins, select 'Check for Updates' in the 'Help' menu.
Please see the [installation](https://github.com/mybatis/mybatipse#installation) section of README for other options.

> You README.md not updated.

Yep. I didn't have the time yesterday. It is updated now.
