### ISSUE TITLE
If the installation and use

### ISSUE THREAD

**Issue by githublaohu** [mybatis/mybatipse#75]
Want to use the way of installation, otherwise very trouble.
![brl29_j 6v xcl5auvqh2](https://cloud.githubusercontent.com/assets/8677242/24903312/ac269812-1edf-11e7-89c3-917c850a2eef.png)
What tips.

**Comment by harawata** [comment]
Do you want to know how to install?
Please see the installation section of README.
https://github.com/mybatis/mybatipse/blob/master/README.md#installation

**Comment by kazuki43zoo** [comment]
No reply. If you cannot resolve this issue, please reopen this issue at any time.
