### ISSUE TITLE
Hyperlink is not working on *.java file

### ISSUE THREAD

**Issue by LouisWayne** [mybatis/mybatipse#76]
I am using Eclipse Neon.3 Release (4.6.3) - and installed MyBatipse from the Eclipse marketplace.

The XML files are in the project's source folder, and I turned on MyBatis Nature - but I don't see the menu `Open <mapper /> in XML mapper`.

Could you advise what I need to do please?

**Comment by harawata** [comment]
Does the XML mapper has the right `namespace`?

```xml
<mapper namespace="com.example.PersonMapper">
...
```

**Comment by LouisWayne** [comment]
@harawata 
Yes - it has the proper `namespace`.  Any suggestions that I can investigate?

**Comment by harawata** [comment]
Try importing the [jpetstore](https://github.com/mybatis/jpetstore-6) project and see if the hyperlink works.

<img src="https://user-images.githubusercontent.com/149268/29379585-f063971e-82fd-11e7-9b4f-c086ade17ffd.png" width="50%">

If it works with jpetstore, look for a difference between jpetstore and your project.
If it does not work, try it with a new clean workspace.

**Comment by LouisWayne** [comment]
Thanks for the updates - and I figured out that the issue is from my Eclipse.  I installed Eclipse in a different directory, and it's working properly.  There is something wrong in my Eclipse setting.  Thanks for creating an amazing plugin!

**Comment by harawata** [comment]
Glad to know that the plugin worked and you found it useful =)
