### ISSUE TITLE
Mapped class resolution for autocompletion

### ISSUE THREAD

**Issue by tmailhot** [mybatis/mybatipse#8]
Actually, does Mybatipse resolve mapped classes only from the config xml file?

I am integrating MyBatis in an OSGi project and I add my mapped classes dynamically by code. Mybatipse does not autocomplete class names. I tried to add a package in MyBatipse type aliases from the project properties, still no autocompletion.

Is there something I can do to get class autocompletion? 
I did not try autocompletion on other fields (resul map id, for example), does my mappers have to be in a config.xml file?

If I can make a suggestion, it would be nice if there would be an option inside MyBatipse to tell the plugin to autocomplete any class listed in the current Eclipse target platform (including workspaces classes) and another option to tell MyBatipse to reference any xml mapper file available in any of the jars listed in the current Eclipse target platform (including workspace projects). I don't know what are the implications of these features, but it would help using MyBatis and MyBatipse while gaining a productivity boost.

I would like to know what I can do to get class name and xml autocompletion

**Comment by guot** [comment]
restart eclipse,Maybe it's ok.

**Comment by kazuki43zoo** [comment]
@tmailhot what's current status?

**Comment by harawata** [comment]
We've got no new information, so I'll close this.

If someone is experiencing the same or similar issue, please create a new issue with the details (version, error message, a repro if possible).
