### ISSUE TITLE
Spring boot and mybatis  typealiase. Could not resolve type alias xx???

### ISSUE THREAD

**Issue by iver3on** [mybatis/mybatipse#80]
same problem.
I define typeAliase com.*.*    aliase  xx   in mybatis-config.xml

and in application.properties mybatis.config-locations=classpath:mybatis-config.xml
why Could not resolve type alias xx???

**Comment by kazuki43zoo** [comment]
It seems to be a duplicate with #77 . 
See https://github.com/mybatis/mybatipse/issues/77#issuecomment-367709881
