### ISSUE TITLE
It would be better to distinguish between the statementIds that have been used and those that have not been used

### ISSUE THREAD

**Issue by shuchang01** [mybatis/mybatipse#87]
![qq 20180726110546](https://user-images.githubusercontent.com/11965700/43239165-e8d60b42-90c3-11e8-9cb6-24b9cafc43a9.png)

**Comment by harawata** [comment]
Thanks for the idea, @shuchang01 !

I would just exclude IDs that are already declared in the XML mapper from the list.
Let me know if there is any problem with this spec.

**Comment by harawata** [comment]
Actually, there can be multiple statements with the same 'id' and a different 'databaseId'. 😑

I'll use the translucent icon for IDs that are already used.
In the picture below, 'select1' and 'select2' are already used.

<img src="https://user-images.githubusercontent.com/149268/43264740-e09c9cd0-9121-11e8-8064-01740510a66c.png" width="320">

**Comment by shuchang01** [comment]
Thanks for your timely reply. It is better to use the translucent icon.

**Comment by harawata** [comment]
Just released 1.2.0 with this enhancement.
Let me know if there is any problem.
Thank you!

**Comment by shuchang01** [comment]
I've updated to version 1.2.0, and the enhancements are working well for now.

**Comment by shuchang01** [comment]
Thank you very much.
