### ISSUE TITLE
how to install this offline

### ISSUE THREAD

**Issue by wangxi761** [mybatis/mybatipse#88]

**Comment by harawata** [comment]
I just tested the following steps with Mac version of Eclipse 4.8.0 and it seems to be working.
Let me know about your environment if it didn't work.

1. Quit Eclipse.
2. Download the latest JARs from the update site.
   - `net.harawata.mybatipse_xxx.jar` from http://dl.bintray.com/harawata/eclipse/plugins/
   - `net.harawata.mybatipse_xxx.jar` from http://dl.bintray.com/harawata/eclipse/features/
3. Copy those JARs to the `dropins` folder in your Eclipse directory. See the attached image for the recommended directory structure.
4. Launch Eclipse.


![image](https://user-images.githubusercontent.com/149268/43911858-8561bd94-9c3b-11e8-924d-19d4c2b9c35b.png)

**Comment by wangxi761** [comment]
@harawata oh  great job! it works

**Comment by sangalx** [comment]
I follow the instruction of @harawata and it works successfully, but only with 1.1.2 version.
The lastest version (1.2) can't work.

**Comment by targaryenj** [comment]
> @sangalx ,
> I just tested the steps with Eclipse 2018-09 on Java 9 and it seems to be working.
> Note that version 1.2.0 requires Java 8+ and Eclipse 4.6+.

Oxygen.2 Release (4.7.2) jdk1.8.0_65 works with 1.1.2 ,The lastest version (1.2) can't work too.

**Comment by harawata** [comment]
@targaryenj ,

Thanks for the info!
Obviously, I got confused about JDT version and 1.2.0 incorrectly requires Eclipse 4.8 (Photon). 😨
I'll release 1.2.1 that works with Eclipse ≥4.6 as soon as possible.

@sangalx ,
I assume you too are using Eclipse 4.6.x or 4.7.x.
Please let me know if that is not the case.

I'm sorry for the inconvenience!

**Comment by harawata** [comment]
@sangalx , @targaryenj 
1.2.1 is out. Please let me know if it still does not work.
Thank you!

**Comment by targaryenj** [comment]
> @sangalx , @targaryenj
> 1.2.1 is out. Please let me know if it still does not work.
> Thank you!

1.2.1 works  .Thank you very much!

**Comment by sangalx** [comment]
> 
> 
> @targaryenj ,
> 
> Thanks for the info!
> Obviously, I got confused about JDT version and 1.2.0 incorrectly requires Eclipse 4.8 (Photon). 😨
> I'll release 1.2.1 that works with Eclipse ≥4.6 as soon as possible.
> 
> @sangalx ,
> I assume you too are using Eclipse 4.6.x or 4.7.x.
> Please let me know if that is not the case.
> 
> I'm sorry for the inconvenience!

I'm using eclipse 4.6.x
after changing to new version of eclipse, it's works.
Thanks for your support.

**Comment by keen-01** [comment]
1.2.2 works,Thank you!!!!

**Comment by luhan-777** [comment]
eclipse4.5  使用1.2.1版本正常！谢谢！

**Comment by dba-kit** [comment]
When I access these two URL below, both response `Forbidden!`. How can I get out of this?
- http://dl.bintray.com/harawata/eclipse/plugins/
-  http://dl.bintray.com/harawata/eclipse/features/

**Comment by harawata** [comment]
Bintray shut down.
The new URLs are...

- https://harawata.jfrog.io/ui/native/eclipse-local/plugins/
- https://harawata.jfrog.io/ui/native/eclipse-local/features/

Thank you for the heads-up, @dba-kit !

**Comment by uday-dandu** [comment]
> Bintray shut down. The new URLs are...
> 
> * https://harawata.jfrog.io/ui/native/eclipse-local/plugins/
> * https://harawata.jfrog.io/ui/native/eclipse-local/features/
> 
> Thank you for the heads-up, @dba-kit !

 Hi, I am unable to login jfrog repository, can help me to register and download the jrs

**Comment by uday-dandu** [comment]
> > Bintray shut down. The new URLs are...
> > 
> > * https://harawata.jfrog.io/ui/native/eclipse-local/plugins/
> > * https://harawata.jfrog.io/ui/native/eclipse-local/features/
> > 
> > Thank you for the heads-up, @dba-kit !
> 
> Hi, I am unable to login jfrog repository, can help me to register and download the jrs

sorry, can ignore pls, I can able to download, thank you

**Comment by MahmoudIbrahimm** [comment]
> > > Bintray shut down. The new URLs are...
> > > 
> > > * https://harawata.jfrog.io/ui/native/eclipse-local/plugins/
> > > * https://harawata.jfrog.io/ui/native/eclipse-local/features/
> > > 
> > > Thank you for the heads-up, @dba-kit !
> > 
> > 
> > Hi, I am unable to login jfrog repository, can help me to register and download the jrs
> 
> sorry, can ignore pls, I can able to download, thank you
How did you download them Please??

**Comment by uday-dandu** [comment]
> 

Try downloading from mobile, laptop doesn't work

**Comment by uday-dandu** [comment]
> > > > Bintray shut down. The new URLs are...
> > > > 
> > > > * https://harawata.jfrog.io/ui/native/eclipse-local/plugins/
> > > > * https://harawata.jfrog.io/ui/native/eclipse-local/features/
> > > > 
> > > > Thank you for the heads-up, @dba-kit !
> > > 
> > > 
> > > Hi, I am unable to login jfrog repository, can help me to register and download the jrs
> > 
> > 
> > sorry, can ignore pls, I can able to download, thank you
> > How did you download them Please??
Download from mobile, somehow it keeps asking for login from the laptop
