### ISSUE TITLE
mac not become effective

### ISSUE THREAD

**Issue by shakarelic** [mybatis/mybatipse#96]

**Comment by harawata** [comment]
I have been using this plugin on macOS (currently Catalina) just fine.
I need you to check a few basics first.

Do you see MyBatipse in the installed plug-ins list? (i.e. About Eclipse -> Installation Details -> Plug-ins)

If the answer to the above question is 'yes', please try ...

1. re-opening the editor(s)
1. restarting Eclipse

If the above does not resolve the problem, please post ...

- the Eclipse version
- what exactly you are trying to do (i.e. steps to reproduce the problem)

**Comment by shakarelic** [comment]
mybatipse version : 1.2.2
Eclipse IDE for Java Developers
Version: 2019-06 (4.12.0)
----- problem:
1.xml  Auto-completion
2.From Java mapper interface to XML mapper element.

**Comment by harawata** [comment]
There are some similar reports (e.g. #8, #79 ).
Unfortunately, we have not found the cause, so far.
Let me know if you find something that might be helpful.

**Comment by harawata** [comment]
Try importing the [jpetstore](https://github.com/mybatis/jpetstore-6) project and see if the hyperlink works.

<img src="https://user-images.githubusercontent.com/149268/29379585-f063971e-82fd-11e7-9b4f-c086ade17ffd.png" width="50%">

If it does not work with jpetstore, please try it with a new clean workspace.

If it works with jpetstore, there may be something special about your project.
If you could share your project on your GitHub, I'll look into it.

**Comment by shakarelic** [comment]
my same project,
winsows is ok,
mac not become effective...

and the jpetstore project.I press command
![TeamTalk_IMG_2019-11-12-144349](https://user-images.githubusercontent.com/8683348/68648435-5a196d00-055b-11ea-8271-f48700eb4ad0.jpg)

**Comment by harawata** [comment]
Have you tried it on a new clean workspace?
It worked for some users in the past.

Or...it might be a conflict with another plugin?
Could you try it using a new Eclipse installation and only this plugin (i.e. no other third party plugins)?

I'm really sorry for the inconvenience.

**Comment by tkvangorder** [comment]
I just ran into this same problem with Eclipse-2019-12 and I *may* have found a solution. Try rebuilding the Java index. Once I did this content assist began working again. 
![image](https://user-images.githubusercontent.com/1878529/71383791-cfcd1b80-2592-11ea-91b1-bf790fe893b1.png)

**Comment by harawata** [comment]
Thank you, @tkvangorder for the comment!
It's definitely easier than creating a new workspace. :D

**Comment by shakarelic** [comment]
与liclipse插件＃97发生冲突
I am the same as @ViCrack
thx

**Comment by harawata** [comment]
@shakarelic ,
Thank you for letting us know!
I am so relieved that we have found the cause (or one of the causes) finally.
Hopefully, we will find a way to avoid the conflict(?) soon.
