### ISSUE TITLE
Conflict with liclipse plugin

### ISSUE THREAD

**Issue by ViCrack** [mybatis/mybatipse#97]
There are some similar reports (e.g. #8, #79 ).
Unfortunately, we have not found the cause, so far.
Let me know if you find something that might be helpful.

_Originally posted by @harawata in https://github.com/mybatis/mybatipse/issues/96#issuecomment-545422304_

**Comment by ViCrack** [comment]
I have a similar problem.

the solution is to uninstall the 
<img width="523" alt="11" src="https://user-images.githubusercontent.com/18179821/71946584-3b56f000-3205-11ea-90c6-75aa6c9ea4c1.png">



Eclipse IDE for Enterprise Java Developers.

Version: 2019-12 (4.14.0)
Build id: 20191212-1212

**Comment by harawata** [comment]
Thank you for the information, @ViCrack !
I have verified that some functionalities stop working after installed LiClipseText and uninstalling LiClipseText resolve the problem.
The author kindly [shared](https://github.com/fabioz/LiClipseText/issues/18) his insight, so I'll see if there is a way to use both plugins side by side.

**Comment by harawata** [comment]
Hi @ViCrack @shakarelic 

I just released 1.2.3 which should fix the compatibility issue with LiClipseText.
Thanks again for your help!
